name: Run Stock Report

on:
  schedule:
    - cron: '0 7 * * *'  # ריצה אוטומטית כל יום בשעה 7:00 UTC
  workflow_dispatch:      # אפשרות להרצה ידנית

jobs:
  run-stock-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance feedparser vaderSentiment requests

      - name: Run stock report script
        run: |
          python stock_report.py

